# -*- coding: utf-8 -*-
"""Final Tugas Kelompok 3_IT_BOOTCAMP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yyI0y5kY4RtQ8vJsahn6YcfnkVDHcmJY

#Bussiness Understanding

dataset ini bertujuan untuk mengidentifikasi variabel-variabel penting yang memengaruhi skor ujian siswa. Dengan memahami pola-pola ini, pihak sekolah atau pembuat kebijakan dapat mengambil tindakan yang lebih tepat, seperti memberikan dukungan akademik tambahan kepada kelompok siswa tertentu, meningkatkan akses ke program persiapan ujian, atau menyesuaikan metode pengajaran berdasarkan karakteristik siswa.

#Data Understanding

Dataset Exam ini memiliki 8 kolom dan 1000 data. Variabel yang ada pada dataset tersebut diantaranya:
*  gender: Jenis kelamin (male/female).
*  race/ethnicity: Kelompok ras/etnis.
*  parental level of education: Tingkat pendidikan orang tua.
*  lunch: Jenis makan siang (standard/free/reduced).
*   test preparation course: Status kursus persiapan ujian (completed/none).
*   math score: Skor matematika.
*   reading score: Skor membaca.
*   writing score: Skor menulis.

#Import Library
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay, classification_report, accuracy_score
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression, LinearRegression
import pickle

# Load dataset (lokal)
df = pd.read_csv('exams.csv')

"""#Baca Dataset"""

df

df.head()

df.iloc[25]

df.info()

df.dtypes

df.describe()

df.rename(columns={
    'race/ethnicity': 'race_ethnicity',
    'parental level of education': 'parental_level_of_education',
    'test preparation course': 'test_preparation_course',
    'math score': 'math_score',
    'reading score': 'reading_score',
    'writing score': 'writing_score'
}, inplace=True)

# Update nama kolom target jika sudah di-rename
target_column_name = 'math_score'
categorical_features_renamed = ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']

"""#Exploratory Data Analysis

##Corelation Variable
"""

plt.figure(figsize=(10, 5))
sns.heatmap(df.select_dtypes(include=[np.number]).corr(), annot=True, cmap='coolwarm')
plt.title('Corelation Variable')
plt.savefig('Corelation Variable.png')

"""Warna yang lebih merah/panas (mendekati 1.000) menunjukkan korelasi positif yang lebih kuat.
Warna yang lebih biru/dingin (mendekati 0.825 dalam kasus ini, meskipun skala bisa lebih rendah lagi) menunjukkan korelasi positif yang lebih lemah (namun masih kuat secara umum).

*   math_score vs reading_score = 0.82 → Korelasi kuat, artinya siswa yang bagus di matematika cenderung bagus juga di membaca.

*   reading_score vs writing_score = 0.95 → Korelasi sangat kuat, artinya nilai membaca dan menulis sangat berkaitan erat.

*   math_score vs writing_score = 0.81 → Korelasi kuat juga, tapi sedikit lebih rendah dibandingkan membaca-menulis.

korelasi variabel menunjukkan bahwa nilai matematika, membaca, dan menulis memiliki hubungan yang kuat satu sama lain. Korelasi tertinggi terjadi antara nilai membaca dan menulis, yang artinya siswa yang pandai membaca biasanya juga pandai menulis. Sementara itu, nilai matematika juga cukup berkaitan dengan dua nilai lainnya, meskipun tidak sekuat hubungan antara membaca dan menulis. Secara keseluruhan, ketiga nilai tersebut saling berhubungan dan bergerak searah.

#Data Distribution

##Visualisasi
"""

# Distribusi skor matematika (target variabel)
plt.figure(figsize=(10, 6))
sns.histplot(df['math_score'], kde=True, bins=20, color='blue')
plt.title('Distribusi Skor Matematika', fontsize=15)
plt.xlabel('Skor Matematika', fontsize=12)
plt.ylabel('Frekuensi', fontsize=12)
plt.grid(axis='y', linestyle='--')
plt.show()

"""Distribusi skor matematika
Visualisasi ini menunjukkan bahwa sebagian besar siswa mendapat nilai matematika antara 60 sampai 80. Bentuk grafiknya menyerupai lonceng, yang berarti nilai siswa tersebar cukup merata, tapi sedikit lebih banyak yang nilainya tinggi. Hanya sedikit siswa yang mendapat nilai sangat rendah atau sangat tinggi. Jadi, bisa disimpulkan bahwa kebanyakan siswa memiliki kemampuan matematika yang cukup baik.

###Visualisasi nilai gender vs math_score
"""

plt.figure(figsize=(15,5))
sns.countplot(x='gender', data=df)
plt.title('Distribusion of gender')
plt.savefig('gender.png')

"""Terlihat bahwa jumlah siswa laki-laki (male) sedikit lebih banyak dibandingkan siswa perempuan (female). Selisihnya tidak terlalu besar, jadi data cukup seimbang antara kedua jenis kelamin. Ini berarti analisis berdasarkan gender bisa dilakukan dengan cukup adil karena tidak ada perbedaan jumlah yang mencolok.

"""

categorical_cols = ['gender'] #definisikan untuk memanggil age
for col in categorical_cols: #pengulangan age
  plt.figure(figsize= (10,5)) #pangil library plt dengan ukuran
  sns.countplot(x=col, hue='math_score', data=df) #untuk pengisian data
  plt.title(f'{col} vs math_score') #membuat judul di grafik
  plt.savefig(f'{col} vs math_score.png')

"""Semakin gelap warnanya, semakin tinggi nilai matematika siswa. Misalnya, pada bagian male, kita bisa melihat banyak bar dengan warna ungu tua (nilai tinggi) dibandingkan famale. Siswa perempuan cenderung memiliki distribusi nilai matematika yang sedikit lebih rendah dibandingkan siswa laki-laki.

###Visualisasi nilai race_ethnicity  vs math_score
"""

plt.figure(figsize=(10,5))
sns.countplot(x='race_ethnicity', data=df)
plt.title('Distribusion of race_ethnicity')
plt.savefig('race_ethnicity.png')

"""Grafik ini menunjukkan distribusi siswa berdasarkan kelompok ras atau etnis. Terlihat bahwa Group C memiliki jumlah siswa terbanyak, diikuti oleh Group D dan Group B. Sementara itu, Group E dan Group A memiliki jumlah siswa yang lebih sedikit. Ini berarti sebagian besar data dalam dataset ini berasal dari Group C dan D, yang bisa memengaruhi hasil analisis jika faktor ras atau etnis dipertimbangkan.

"""

categorical_cols = ['race_ethnicity'] #definisikan untuk memanggil age
for col in categorical_cols: #pengulangan age
  plt.figure(figsize= (25,8)) #pangil library plt dengan ukuran
  sns.countplot(x=col, hue='math_score', data=df) #untuk pengisian data
  plt.title(f'{col} vs math_score') #membuat judul di grafik
  plt.savefig(f'{col} vs math_score.png')

"""Grafik menunjukkan bahwa kelompok etnis C dan D cenderung memiliki nilai matematika lebih tinggi dibanding kelompok lain, terlihat dari dominasi warna lebih gelap. Sementara itu, kelompok A memiliki sebaran nilai yang lebih rendah. Ini menunjukkan adanya perbedaan performa matematika antar kelompok etnis.

###Visualisasi nilai parental_level_of_education vs math_score
"""

plt.figure(figsize=(15,5))
sns.countplot(x='parental_level_of_education', data=df)
plt.title('Distribusion of parental_level_of_education')
plt.savefig('parental_level_of_education.png')

"""Grafik menunjukkan bahwa sebagian besar orang tua siswa berpendidikan SMA, diploma, atau pernah kuliah. Hanya sedikit yang memiliki gelar S1 atau S2. Ini berarti mayoritas siswa berasal dari keluarga dengan pendidikan menengah.

"""

categorical_cols = ['parental_level_of_education'] #definisikan untuk memanggil age
for col in categorical_cols: #pengulangan age
  plt.figure(figsize= (25,8)) #pangil library plt dengan ukuran
  sns.countplot(x=col, hue='math_score', data=df) #untuk pengisian data
  plt.title(f'{col} vs math_score') #membuat judul di grafik
  plt.savefig(f'{col} vs math_score.png')

"""Grafik ini menunjukkan bahwa siswa dengan orang tua berpendidikan lebih tinggi, seperti yang memiliki gelar sarjana atau master, cenderung memiliki nilai matematika yang lebih tinggi. Sebaliknya, siswa dengan orang tua berpendidikan SMA atau di bawahnya umumnya memiliki sebaran nilai yang lebih rendah. Hal ini mengindikasikan adanya pengaruh positif tingkat pendidikan orang tua terhadap prestasi matematika anak.

###Visualisasi nilai lunch vs math_score
"""

plt.figure(figsize=(15,5))
sns.countplot(x='lunch', data=df)
plt.title('Distribusion of lunch')
plt.savefig('lunch.png')

"""Grafik menunjukkan bahwa sebagian besar siswa menerima makan siang standar, sementara sisanya mendapatkan makan siang gratis atau dengan potongan harga. Artinya, lebih banyak siswa berasal dari keluarga dengan kondisi ekonomi yang cukup baik.

"""

categorical_cols = ['lunch'] #definisikan untuk memanggil age
for col in categorical_cols: #pengulangan age
  plt.figure(figsize= (15,5)) #pangil library plt dengan ukuran
  sns.countplot(x=col, hue='math_score', data=df) #untuk pengisian data
  plt.title(f'{col} vs math_score') #membuat judul di grafik
  plt.savefig(f'{col} vs math_score.png')

"""Grafik menunjukkan bahwa siswa dengan makan siang standar cenderung memiliki skor matematika yang lebih tinggi (warna lebih gelap) dibandingkan dengan siswa yang mendapat makan siang gratis atau subsidi, yang didominasi oleh warna lebih terang. Hal ini menunjukkan adanya kemungkinan hubungan antara status ekonomi dan pencapaian akademik.

###Visualisasi nilai race_ethnicity vs math_score
"""

plt.figure(figsize=(15,5))
sns.countplot(x='test_preparation_course', data=df)
plt.title('Distribusion of test_preparation_course')
plt.savefig('test_preparation_course.png')

"""Grafik menunjukkan bahwa lebih banyak siswa yang **tidak mengikuti kursus persiapan tes** dibandingkan dengan yang **sudah menyelesaikannya**. Ini terlihat dari batang “none” yang jauh lebih tinggi daripada “completed”.

"""

categorical_cols = ['test_preparation_course'] #definisikan untuk memanggil age
for col in categorical_cols: #pengulangan age
  plt.figure(figsize= (15,5)) #pangil library plt dengan ukuran
  sns.countplot(x=col, hue='math_score', data=df) #untuk pengisian data
  plt.title(f'{col} vs math_score') #membuat judul di grafik
  plt.savefig(f'{col} vs math_score.png')

"""Grafik menunjukkan bahwa siswa yang mengikuti kursus persiapan ujian cenderung memiliki nilai matematika lebih tinggi, terlihat dari warna lebih gelap pada kelompok “completed”. Sebaliknya, siswa yang tidak mengikuti kursus lebih banyak mendapat nilai menengah ke bawah. Ini menunjukkan kursus persiapan dapat berdampak positif pada nilai matematika.

#Data Distribution

##Duplicate Data
"""

# Cek duplikasi
print(f"\nJumlah baris duplikat: {df.duplicated().sum()}")
df_cleaned = df.drop_duplicates()
print(f"Jumlah baris setelah menghapus duplikat: {len(df_cleaned)}")

"""##Missing Values"""

# Cek missing values
missing_values = df_cleaned.isnull().sum()
percentage_missing = (missing_values / len(df_cleaned)) * 100
missing_data_info = pd.DataFrame({
    'missing_value': missing_values,
    'percentage_missing': percentage_missing
})
print("\nInformasi Missing Values:")
print(missing_data_info)

"""#Outlier"""

numeric_column = df.select_dtypes(include=['int64']).columns   # berfungsi untuk mengambil kolom dengan tipe numerik
fig, axs = plt.subplots(ncols=len(numeric_column), figsize=(4 * len(numeric_column), 5))

#membuat sebuah grid float secara horizontal dengan disesuaikan ukurannya pada subplot

for i,  column in enumerate(numeric_column):
  sns.boxplot(y=df[column], ax=axs[i], whis=1.5)
  axs [i].set_title(f'Box Plot for {column}')
  axs [i].set_xlabel('')
  axs [i].set_ylabel('')

plt.tight_layout(pad=0.4, w_pad=0.5, h_pad=0.5)
plt.show()

"""#Prossecing Data

##Encoding
"""

#Menyimpan salinan sebelum Encodinng
df_before = df.copy()

#Encoding
encoders = {}
for col in ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']:
  encoders[col] = LabelEncoder()
  df[col] =  encoders[col].fit_transform(df[col])

#Tampilkan 5 baris pertama baik sebelum maupun sesudah
print("Sebelum di encode: ")
print(df_before[['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']].head())

print("Setelah di encode: ")
print(df[['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']].head())

"""##Normalisasi"""

# 4. Tentukan kolom numerik untuk penskalaan
numerik = ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
print(df[numerik].describe())

"""##Feature Engineering"""

# 5. Membakukan fitur numerik
scaler = StandardScaler()
df[numerik] = scaler.fit_transform(df[numerik])
print(df[numerik].describe())

# Hubungan antara skor matematika vs skor membaca
plt.figure(figsize=(14, 7))
plt.subplot(1, 2, 1)
sns.scatterplot(x='reading_score', y=target_column_name, data=df, hue='gender', palette='coolwarm', alpha=0.7)
plt.title('Skor Matematika vs Skor Membaca', fontsize=15)
plt.xlabel('Skor Membaca', fontsize=12)
plt.ylabel('Skor Matematika', fontsize=12)
plt.grid(True, linestyle='--')

# Hubungan antara skor matematika vs skor menulis
plt.figure(figsize=(14, 7))
plt.subplot(1, 2, 2)
sns.scatterplot(x='writing_score', y=target_column_name, data=df, hue='gender', palette='coolwarm', alpha=0.7)
plt.title('Skor Matematika vs Skor Menulis', fontsize=15)
plt.xlabel('Skor Menulis', fontsize=12)
plt.ylabel('Skor Matematika', fontsize=12)
plt.grid(True, linestyle='--')
plt.show()

df.head()

"""# Modeling"""

# --- Bagian 2: Model Klasifikasi (Prediksi Kategori Skor Matematika) ---
print("\n--- Bagian 2: Model Klasifikasi (Prediksi Kategori Skor Matematika) ---")
# Menggunakan df_cleaned untuk konsistensi
df_class = df_cleaned.copy()

# Binning nilai matematika ke dalam kategori
bins = [0, 59, 79, 100] # Disesuaikan agar batas bawah tidak ambigu (misal <60, 60-79, >=80)
labels = ['Rendah', 'Sedang', 'Tinggi'] # Low, Medium, High
df_class['score_class'] = pd.cut(df_class['math_score'], bins=bins, labels=labels, include_lowest=True, right=True)

print("\nDistribusi Kelas Skor Matematika:")
print(df_class['score_class'].value_counts())

# Fitur non-akademik untuk klasifikasi
X_class_features = ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
X_class = df_class[X_class_features]
y_class = df_class['score_class']

# Pra-pemrosesan untuk Klasifikasi (One-Hot Encoding)
# Menggunakan ColumnTransformer agar lebih robust dan bisa di-pipeline
categorical_transformer_class = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore', drop='first'))
])

preprocessor_class = ColumnTransformer(
    transformers=[
        ('cat', categorical_transformer_class, X_class_features)
    ])

# Pipeline untuk model klasifikasi
rf_class_pipeline = Pipeline(steps=[('preprocessor', preprocessor_class),
                                    ('classifier', RandomForestClassifier(random_state=42))])

# Split data
X_train_class, X_test_class, y_train_class, y_test_class = train_test_split(
    X_class, y_class, test_size=0.2, random_state=42, stratify=y_class # stratify penting untuk target kelas
)

# Latih model klasifikasi
print("\nMelatih Model Klasifikasi (Random Forest untuk score_class)...")
rf_class_pipeline.fit(X_train_class, y_train_class)

# Prediksi
y_pred_class = rf_class_pipeline.predict(X_test_class)

# Evaluasi
print("\nLaporan Klasifikasi untuk 'score_class':")
print(classification_report(y_test_class, y_pred_class))

cm_class = confusion_matrix(y_test_class, y_pred_class, labels=rf_class_pipeline.named_steps['classifier'].classes_)
disp_class = ConfusionMatrixDisplay(confusion_matrix=cm_class, display_labels=rf_class_pipeline.named_steps['classifier'].classes_)
disp_class.plot(cmap='Blues')
plt.title('Confusion Matrix untuk score_class')
plt.show()

try:
    feature_names_out = rf_class_pipeline.named_steps['preprocessor'].get_feature_names_out()
    importances_class = rf_class_pipeline.named_steps['classifier'].feature_importances_

    feature_importance_df = pd.DataFrame({'feature': feature_names_out, 'importance': importances_class})
    feature_importance_df = feature_importance_df.sort_values(by='importance', ascending=False)

    plt.figure(figsize=(10, 8)) # Ukuran disesuaikan
    sns.barplot(x='importance', y='feature', data=feature_importance_df.head(15), palette='viridis') # Tampilkan top 15
    plt.title('Random Forest - Feature Importance untuk score_class')
    plt.xlabel("Feature Importance")
    plt.ylabel("Feature")
    plt.tight_layout()
    plt.show()
except Exception as e:
    print(f"Tidak dapat menampilkan feature importance: {e}")

# --- Bagian 3: Model Klasifikasi (Prediksi Status Lulus/Tidak Lulus) ---
print("\n--- Bagian 3: Model Klasifikasi (Prediksi Status Lulus/Tidak Lulus) ---")
df_status = df_cleaned.copy()

# Buat label 'status' dari math score (misal >= 60 Lulus)
df_status['status'] = df_status['math_score'].apply(lambda x: 'Lulus' if x >= 60 else 'Tidak Lulus')

print("\nDistribusi Status Kelulusan:")
print(df_status['status'].value_counts())

# Pilih fitur dan target (menggunakan semua fitur kecuali skor dan status itu sendiri)
# Untuk contoh ini, kita akan menggunakan fitur kategorikal yang sudah di-rename
X_status_features = ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
X_status = df_status[X_status_features]
y_status = df_status['status'] # Target sudah berupa string, akan di-encode oleh pipeline jika perlu

# Pipeline untuk model klasifikasi status
rf_status_pipeline = Pipeline(steps=[('preprocessor', preprocessor_class), # Menggunakan preprocessor yang sama
                                     ('classifier', RandomForestClassifier(random_state=42))])

# Split data
X_train_status, X_test_status, y_train_status, y_test_status = train_test_split(
    X_status, y_status, test_size=0.2, random_state=42, stratify=y_status
)

# Latih model
print("\nMelatih Model Klasifikasi (Random Forest untuk status kelulusan)...")
rf_status_pipeline.fit(X_train_status, y_train_status)

# Prediksi
y_pred_status = rf_status_pipeline.predict(X_test_status)

# Evaluasi
print("\nLaporan Klasifikasi untuk 'status kelulusan':")
# Mendapatkan nama kelas dari pipeline (jika target di-encode secara internal)
# atau dari y_status.unique() jika tidak
target_names_status = sorted(y_status.unique()) # Pastikan urutan benar
print(classification_report(y_test_status, y_pred_status, target_names=target_names_status))

accuracy_status = accuracy_score(y_test_status, y_pred_status)
print(f"Akurasi Model Status Kelulusan: {accuracy_status:.4f}")

cm_status = confusion_matrix(y_test_status, y_pred_status, labels=target_names_status)
disp_status = ConfusionMatrixDisplay(confusion_matrix=cm_status, display_labels=target_names_status)
disp_status.plot(cmap='Greens')
plt.title('Confusion Matrix untuk Status Kelulusan')
plt.show()

# --- Bagian 4: Model Regresi untuk Memprediksi Skor Matematika (Seperti Contoh Saya) ---
print("\n--- Bagian 4: Model Regresi untuk Memprediksi Skor Matematika ---")
df_reg = df_cleaned.copy()

"""## Data Fitur dan Target"""

# Fitur (X) dan Target (y) untuk Regresi
# Menggunakan fitur kategorikal dan skor lainnya untuk memprediksi math_score
X_reg_categorical_features = ['gender', 'race_ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course']
X_reg_numerical_features = ['reading_score', 'writing_score']
X_reg = df_reg[X_reg_categorical_features + X_reg_numerical_features]
y_reg = df_reg['math_score']

# Pra-pemrosesan untuk Regresi
# OneHotEncoder untuk fitur kategorikal, StandardScaler untuk fitur numerik
preprocessor_reg = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore', drop='first'), X_reg_categorical_features),
        ('num', StandardScaler(), X_reg_numerical_features)
    ],
    remainder='passthrough' # Jika ada kolom lain yang tidak disebutkan, biarkan apa adanya
)

# Pipeline untuk model regresi
lr_reg_pipeline = Pipeline(steps=[('preprocessor', preprocessor_reg),
                                  ('regressor', LinearRegression())])

# Split data
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg, y_reg, test_size=0.2, random_state=42
)

# Latih model regresi
print("\nMelatih Model Regresi (Linear Regression untuk math_score)...")
lr_reg_pipeline.fit(X_train_reg, y_train_reg)

# Simpan model regresi menggunakan pickle
pickle.dump(lr_reg_pipeline, open("model.pkl", "wb"))

# Prediksi pada data uji
y_pred_reg_test = lr_reg_pipeline.predict(X_test_reg)

# Evaluasi model regresi
mse_reg = mean_squared_error(y_test_reg, y_pred_reg_test)
r2_reg = r2_score(y_test_reg, y_pred_reg_test)

print("\nEvaluasi Model Regresi pada Data Uji:")
print(f"Mean Squared Error (MSE): {mse_reg:.2f}")
print(f"R-squared (R2 Score): {r2_reg:.2f}") # R2 akan jauh lebih tinggi karena menyertakan reading & writing score

# Menampilkan sampel prediksi vs aktual
results_reg_df = pd.DataFrame({'Actual Math Score': y_test_reg, 'Predicted Math Score': y_pred_reg_test})
results_reg_df['Predicted Math Score'] = results_reg_df['Predicted Math Score'].round(2)
print("\nSampel Perbandingan Skor Matematika Aktual vs. Prediksi (Data Uji Regresi - 10 data pertama):")
print(results_reg_df.head(10).to_string())

# Pengujian Model Regresi dengan Data Dummy
print("\n--- Pengujian Model Regresi dengan Data Dummy ---")
data_dummy_reg = pd.DataFrame({
    'gender': ['female', 'male'],
    'race_ethnicity': ['group C', 'group A'],
    'parental_level_of_education': ["bachelor's degree", 'high school'],
    'lunch': ['standard', 'free/reduced'],
    'test_preparation_course': ['none', 'completed'],
    'reading_score': [70, 55], # Tambahkan skor membaca
    'writing_score': [75, 50]  # Tambahkan skor menulis
})

print("\nData Dummy untuk Regresi:")
print(data_dummy_reg.to_string())

# Prediksi pada data dummy
dummy_predictions_reg = lr_reg_pipeline.predict(data_dummy_reg)
dummy_predictions_reg_rounded = [round(p, 2) for p in dummy_predictions_reg]

data_dummy_reg['Predicted Math Score'] = dummy_predictions_reg_rounded
print("\nHasil Prediksi Regresi untuk Data Dummy:")
print(data_dummy_reg.to_string())